#!/usr/bin/env node

var http = require('http'),
    os = require('os'),
    connect = require('connect'),
    app = connect(),
    WebSocketServer = require('ws').Server,
    connections = {},
    connectionIDCounter = 0,
    PORT = process.argv[2] || 20000,
    info = 'INFO',
    version = 'VERSION',
    processV = process.version,
    cpus = os.cpus().length,
    sysStr = os.type() + ' ' + os.arch() + ' ' + os.release(),
    vJson = JSON.stringify({
        type: version,
        data: {
            info: processV,
            sys: sysStr,
            cpus: cpus
        }
    }),
    graphHistory = [];

// a function that returns an object with the new data in place
var sysData = function () {
    return {
        type: info,
        data: {
            memory: {
                info: process.memoryUsage(),
                sys: {
                    freemem: os.freemem(),
                    totalmem: os.totalmem()
                }

            },
            uptime: {
                info: process.uptime(),
                sys: os.uptime()
            },
            load: os.loadavg()
        }
    };
};

// fill the history up first so we can start shifting it
(function initHistory() {
    var tempData = sysData().data,
        i;
    for (i = 0; i < 72; i += 1) {
        graphHistory.push(tempData);
    }
}());

// function for sending to all connected clients
function dataSend(data) {
    Object.keys(connections).forEach(function (id) {
        if (connections[id].readyState === 1) {
            connections[id].send(data);
        }
    });
}

// define the server and start listening
app.use(connect.static(__dirname + '/public'));
var server = http.createServer(app).listen(PORT);

// the websocket-server logics
var wss = new WebSocketServer({ server: server });

wss.on('connection', function (connection) {
    connection.id = connectionIDCounter += 1;
    connections[connection.id] = connection;
    connection.on('message', function (message) {
        var sending;
        if (message === version) {
            sending = graphHistory;
            connection.send(vJson);
            connection.send(JSON.stringify({ type: "HISTORY", data: sending }));
        } else {
            message = null;
        }
    });
    connection.on('error', function (error) {
        connection.close();
    });
    connection.on('close', function () {
        delete connections[connection.id];
    });

});

// a function for setting the interval for new data to be sent
(function sendInterval() {
    var sendData = sysData();
    graphHistory.shift();
    graphHistory.push(sendData.data);
    dataSend(JSON.stringify(sendData));
    setTimeout(function () {
        sendInterval();
    }, 5000);
}());
