#!/usr/bin/env node

"use strict";
process.env.NODE_ENV = 'production';
var http = require('http'),
    os = require('os'),
    connect = require('connect'),
    app = connect(),
    WebSocketServer = require('websocket').server,
    packageJ = require('./package'),
    connections = {},
    connectionIDCounter = 0,
    PORT = process.argv[2] || 20000,
    info = 'INFO',
    version = 'VERSION',
    processV = process.version,
    serverV = packageJ.version,
    cpus = os.cpus().length,
    sysStr = os.type() + ' ' + os.arch() + ' ' + os.release(),
    vJson = JSON.stringify({
        type: version,
        data: {
            server: serverV,
            info: processV,
            sys: sysStr,
            cpus: cpus
        }
    }),
    graphHistory = [];

// a function that returns an object with the new data in place
var sysData = function () {
    return {
        type: info,
        data: {
            memory: {
                info: process.memoryUsage(),
                sys: {
                    freemem: os.freemem(),
                    totalmem: os.totalmem()
                }

            },
            uptime: {
                info: process.uptime(),
                sys: os.uptime()
            },
            load: os.loadavg(),
            time: Date.now()
        }
    };
};

// fill the history up first so we can start shifting it
(function initHistory() {
    var tempData = sysData().data,
        i;
        tempData.time -= 360000;
    for (i = 0; i < 72; i += 1) {
        tempData.time += 5000;
        graphHistory.push({ memory: tempData.memory, uptime: tempData.uptime, load: tempData.load, time: tempData.time });
    }
}());

// function for sending to all connected clients
function dataSend(data) {
    Object.keys(connections).forEach(function (id) {
        if (connections[id].connected) {
            connections[id].send(data);
        }
    });
}

// define the server and start listening
var server = http.createServer(app).listen(PORT);
var month = 2592000000;
app.use(connect.static(__dirname + '/public', { maxAge: month }));
server.allowHalfOpen = false;
server.on('error', function (err) { err = null; return; });
// the websocket-server logics
var wss = new WebSocketServer({ httpServer: server });

wss.on('request', function (request) {
    var connection = request.accept(null, request.remoteAddress);
        connection.id = connectionIDCounter += 1;
        connections[connection.id] = connection;
    
    connection.on('message', function (message) {
        var sending;
        if (message.type === 'utf8' && message.utf8Data === version) {
            sending = graphHistory;
            connection.send(vJson);
            connection.send(JSON.stringify({ type: "HISTORY", data: sending }));
        } else {
            message = null;
        }
    })
    .on('error', function (error) {
        connection.close();
    })
    .on('close', function () {
        delete connections[connection.id];
    });

});

// a function for setting the interval for new data to be sent
(function sendInterval() {
    var sendData = sysData();
    graphHistory.shift();
    graphHistory.push(sendData.data);
    dataSend(JSON.stringify(sendData));
    setTimeout(function () {
        sendInterval();
    }, 5000);
}());
